### ISSUE TITLE
List requirements for frontend design

### ISSUE THREAD

**Issue by udosson** [kumodao/kumo-protocol#113]
## Description
As a UX/UI designer, I want to know the requirement of the development team so I can best prepare the design for them that makes integration as efficient as possible.

## Expected Outcome

- [ ] List requirements that are needed from the frontend perspective 
- [ ] Define who the information should be transfered

**Comment by asimpk** [comment]
- [ ] Sidebar and Main Content component design should be consistent in design (background, color etc)
- [ ] Selection Cards Components(Vault, Stability Pool Staking) consistent in design
- [ ] FormCards (variants) consistent in Design
![01_k_HomePage](https://user-images.githubusercontent.com/74536379/168750900-18ff2091-d957-406d-aabe-1a0808544e61.PNG)
![02_k_TroveCard](https://user-images.githubusercontent.com/74536379/168750952-91badf31-2f2e-4b08-82d7-a951c082e80b.PNG)
![03_k_StabilityPoolcard](https://user-images.githubusercontent.com/74536379/168750964-aa01d9d0-5b86-47b0-a26e-8d7e916c8403.PNG)
![Uploading 04_k_StakingCards.PNG…]()

**Comment by asimpk** [comment]
Hi @udosson we will discuss about it during the session with some mock design so narrow our requirements
