### ISSUE TITLE
Upgrade semantic-release from 17.4.2 to 19.0.2

### ISSUE THREAD

**Issue by udosson** [kumodao/kumo-protocol#118]
Upgrade `semantic-release` from `17.4.2` to `19.0.2` and fix the current issues at https://github.com/kumodao/borrowprot/runs/6366169735?check_suite_focus=true#step:6:10

Node `>=16 || ^14.1` is required. We are at version `12.22.12`

#6

**Comment by asimpk** [comment]
> Upgrade `semantic-release` from `17.4.2` to `19.0.2` and fix the current issues at https://github.com/kumodao/borrowprot/runs/6366169735?check_suite_focus=true#step:6:10
> 
> Node `>=16 || ^14.1` is required. We are at version `12.22.12`
> 
> #6

@udosson  Still getting the same error during at ` yarn install --frozen-lockfile`, do I need to change node version  `Node `>=16 || ^14.1`` ?but not sure about expected breaking of changing node version

**Comment by udosson** [comment]
Yes. We would need to update `node` in order to update `semantic-release`

**Comment by udosson** [comment]
merge in #164
