### ISSUE TITLE
Rework the deployment process of smart contracts with UUPS Proxy Pattern

### ISSUE THREAD

**Issue by udosson** [kumodao/kumo-protocol#150]
Option 1:
- add an initializer function that just sets the owner
- Allow only the owner to call `setParams`

Option 2:
- call `setParams` as `initializer` during deployment
- Adjust deployment sequence so we have all params ready for each contract in chronicle order

Other options?

**Comment by arthurka-o** [comment]
We chose and implemented `Option 1`
