### ISSUE TITLE
Fix compilation issue of lib-subgraph

### ISSUE THREAD

**Issue by udosson** [kumodao/kumo-protocol#176]
With the recent updates in https://github.com/kumodao/kumo-protocol/tree/139-ll-set-all-system-parameters-from-one-smart-contract the compilation of `@kumodao/lib-subgraph` fails due to the newly added `asset` parameter.

The error is at:
https://github.com/kumodao/kumo-protocol/runs/7556562048?check_suite_focus=true#step:4:162

**Comment by wollooo** [comment]
fixed https://github.com/kumodao/kumo-protocol/pull/177
