### ISSUE TITLE
fix broken test with the switch to multicollaterral

### ISSUE THREAD

**Issue by wollooo** [kumodao/kumo-protocol#188]
is continuously updated!

The following  Test are failing:

- `CollSurplusPool.js`
   - [x] CollSurplusPool::getAssetBalance(): Returns the ETH balance of the CollSurplusPool after redemption
   - [x] CollSurplusPool: claimColl(): Reverts if owner cannot receive ETH surplus --> skipped for now because it relates to ETH. Need to evaluate later if test still makes sense
 
- `ConnectContractsTest.js`
   - [x] Sets the correct StabilityPool address in TroveManager
   - [x] Sets the correct StabilityPool address in ActivePool
   - [x] Sets the correct StabilityPool address in CommunityIssuance

- `OwnershipTest.js`
   - [x] TroveManager setAddresses(): reverts when called by non-owner, with wrong addresses, or twice
   - [x] StabilityPool setAddresses(): reverts when called by non-owner, with wrong addresses, or twice
   - [x] Active Pool setAddresses(): reverts when called by non-owner, with wrong addresses, or twice
   - [x] SortedTroves setParams(): reverts when called by non-owner, with wrong addresses, or twice
   - [x] KUMOStaking setAddresses(): reverts when called by non-owner, with wrong addresses, or twice:

`ProxyBorrowerWrappersScript.js`
   - [ ] claimCollateralAndOpenTrove(): reverts if nothing to claim:
   - [ ] claimCollateralAndOpenTrove(): without sending any value:
   - [ ] claimCollateralAndOpenTrove(): sending value in the transaction:
   - [ ] claimStakingGainsAndRecycle(): with both ETH and KUSD gains:

- `DefaultsPool.js`
   - [x] sendETHToActivePool(): fails if receiver cannot receive ETH --> skipped for now because it relates to ETH. Need to evaluate later if test still makes sense
   - [x] increaseKUSD(): increases the recorded KUSD balance by the correct amount
   - [x] decreaseKUSD(): decreases the recorded KUSD balance by the correct amount
   - [x] sendETHToActivePool(): decreases the recorded ETH balance by the correct amount

- `PoolTest.js` 
   - [x] increaseKUSD(): increases the recorded KUSD balance by the correct amount:
   - [x] decreaseKUSD(): decreases the recorded KUSD balance by the correct amount:

- `KUMOStakingFeeRewardsTest.js`
   - [x] KUSD fee per KUMO staked increases when a redemption fee is triggered and totalStakes > 0
   - [x] KUMO Staking: Multiple stakers earn the correct share of all ETH and KUMO fees, based on their stake size:
   - [x] unstake(): reverts if caller has ETH gains and can't receive ETH:

-  `StabilityPool - Withdrawal of stability deposit - Reward calculationsl`
   - [x] All Tests!

-  `StabilityPool`
   - [x] All Tests!

-  `TroveManager`
   - [x] A lot of

-  `TroveManager_RecoveryModeTest.js`
     - [x] liquidate(), with 110% < ICR < TCR, can claim collateral, re-open, be reedemed and claim again:
     - [x] liquidate(), with 110% < ICR < TCR, can claim collateral, after another claim from a redemption:
     - [x] batchLiquidateTroves(): skips liquidation of troves with ICR > TCR, regardless of Stability Pool size

**Comment by udosson** [comment]
- `TroveManagerTest.js`
- [ ] liquidate(): updates the L_ETH and L_KUSDDebt reward-per-unit-staked totals

**Comment by udosson** [comment]
Fixed in https://github.com/kumodao/kumo-protocol/pull/260
