### ISSUE TITLE
Fix all tests in AccessControlTest.js related to the multi-asset feature

### ISSUE THREAD

**Issue by udosson** [kumodao/kumo-protocol#207]

**Comment by wollooo** [comment]
Branch: https://github.com/wollooo/kumo-protocol/tree/KumoParameters-asset
 Failing tests:
 
     - [ ] fallback(): reverts when called by an account that is not Borrower Operations nor Default Pool:
     - [ ] fallback(): reverts when called by an account that is not the Active Pool:

**Comment by udosson** [comment]
> 

@wollooo I fixed the tests with this commit: https://github.com/udosson/kumo-protocol/commit/7fb31f7fb45830ee9be483b6253e1e1f0a232f4e
Please `git cherry-pick` the commit and create a PR to https://github.com/kumodao/kumo-protocol/tree/139-ll-set-all-system-parameters-from-one-smart-contract

`DefaultPool` and `ActivePool` don't use the fallback function `receive()` anymore because this only works for the native current `ETH`. We now use `receivedERC20` as a function to receive any kind of ERC20 token
