### ISSUE TITLE
Fix all tests in BorrowerOperationsTest.js related to the multi-asset feature

### ISSUE THREAD

**Issue by udosson** [kumodao/kumo-protocol#208]

**Comment by wollooo** [comment]
ToDo: fix failing Test https://github.com/kumodao/kumo-protocol/issues/188

- `BorrowerOperationsTest,js`
   - [ ] addColl(), active Trove: applies pending rewards and updates user's L_ETH, L_KUSDDebt snapshots
   - [ ] addColl(), reverts if trove is non-existent or closed
   - [ ] withdrawColl(): applies pending rewards and updates user's L_ETH, L_KUSDDebt snapshots
   - [ ] withdrawKUSD(): borrowing at non-zero base rate sends KUSD fee to KUMO staking contract
   - [ ] withdrawKUSD(): borrowing at non-zero base records the (drawn debt + fee) on the Trove struct 
   - [ ] withdrawKUSD(): Borrowing at non-zero base rate increases the KUMO staking contract KUSD fees-per-unit-staked
   - [ ] withdrawKUSD(): Borrowing at non-zero base rate sends requested amount to the user
   - [ ] withdrawKUSD(): Borrowing at zero base rate changes KUSD fees-per-unit-staked
   - [ ] adjustTrove(): borrowing at non-zero base rate sends KUSD fee to KUMO staking contract
   - [ ] adjustTrove(): borrowing at non-zero base records the (drawn debt + fee) on the Trove struct
   - [ ] adjustTrove(): Borrowing at non-zero base rate increases the KUMO staking contract KUSD fees-per-unit-staked
   - [ ] adjustTrove(): Borrowing at non-zero base rate sends requested amount to the user
   - [ ] adjustTrove(): Borrowing at zero base rate changes KUMO staking contract KUSD fees-per-unit-staked
   - [ ] adjustTrove(): debt increase in Recovery Mode charges no fee
   - [ ] adjustTrove(): reverts when KUSD repaid is > debt of the trove
   - [ ] closeTrove(): zero's the troves reward snapshots
   - [ ] closeTrove(): applies pending rewards
   - [ ] openTrove(): borrowing at non-zero base rate sends KUSD fee to KUMO staking contract
   - [ ] openTrove(): borrowing at non-zero base records the (drawn debt + fee  + liq. reserve) on the Trove struct
   - [ ] openTrove(): Borrowing at non-zero base rate increases the KUMO staking contract KUSD fees-per-unit-staked
   - [ ] openTrove(): Borrowing at non-zero base rate sends requested amount to the user
   - [ ] openTrove(): Borrowing at zero base rate changes the KUMO staking contract KUSD fees-per-unit-staked
   - [ ] openTrove(): records up-to-date initial snapshots of L_ETH and L_KUSDDebt
   - [ ] getNewTCRFromTroveChange() returns the correct TCR

**Comment by wollooo** [comment]
fixed @ https://github.com/kumodao/kumo-protocol/commit/9591a202ef35dab8decbb2ac40b07221986b5b8d
