### ISSUE TITLE
Fix all tests in HintHelpersTest.js related to the multi-asset feature

### ISSUE THREAD

**Issue by udosson** [kumodao/kumo-protocol#211]

**Comment by wollooo** [comment]
ToDo: fix failing Test https://github.com/kumodao/kumo-protocol/issues/188

- `HintHelpers_getApproxHintTest.js`
   - [ ] setup: makes accounts with nominal ICRs increasing by 1% consecutively
   - [ ] getApproxHint(): returns the address of a Trove within sqrt(length) positions of the correct insert position
   - [ ] getApproxHint(): returns the head of the list if the CR is the max uint256 value
   - [ ] getApproxHint(): returns the tail of the list if the CR is lower than ICR of any Trove

**Comment by wollooo** [comment]
fixed @ https://github.com/kumodao/kumo-protocol/commit/9591a202ef35dab8decbb2ac40b07221986b5b8d
