### ISSUE TITLE
Fix all tests in KUMOStakingFeeRewardsTest.js related to the multi-asset feature

### ISSUE THREAD

**Issue by udosson** [kumodao/kumo-protocol#213]

**Comment by wollooo** [comment]
- `KUMOStakingFeeRewardsTest.js`
   - [ ] KUSD fee per KUMO staked increases when a redemption fee is triggered and totalStakes > 0
   - [ ] KUMO Staking: Multiple stakers earn the correct share of all ETH and KUMO fees, based on their stake size:
   - [ ] unstake(): reverts if caller has ETH gains and can't receive ETH:
