### ISSUE TITLE
Fix all tests in PoolsTest.js related to the multi-asset feature

### ISSUE THREAD

**Issue by udosson** [kumodao/kumo-protocol#218]

**Comment by wollooo** [comment]
ToDo: fix failing Test https://github.com/kumodao/kumo-protocol/issues/188

- `PoolTest.js` 
   - [ ] increaseKUSD(): increases the recorded KUSD balance by the correct amount:
   - [ ] decreaseKUSD(): decreases the recorded KUSD balance by the correct amount:

**Comment by udosson** [comment]
Fixed in https://github.com/kumodao/kumo-protocol/commit/33ad56d215d973be7ce02c3287192e05d8279e51
