### ISSUE TITLE
Fix all tests in SortedTrovesTest.js related to the multi-asset feature

### ISSUE THREAD

**Issue by udosson** [kumodao/kumo-protocol#220]

**Comment by wollooo** [comment]
ToDo: fix failing Test https://github.com/kumodao/kumo-protocol/issues/188

- `SortedTroves,js`
   - [ ] setParams(): reverts if size is zero:

**Comment by udosson** [comment]
merged in https://github.com/kumodao/kumo-protocol/pull/238
