### ISSUE TITLE
Fix all tests in TroveManager_RecoveryModeTest.js related to the multi-asset feature 

### ISSUE THREAD

**Issue by udosson** [kumodao/kumo-protocol#228]

**Comment by wollooo** [comment]
ToDo: fix failing Test https://github.com/kumodao/kumo-protocol/issues/188
-  `TroveManager_RecoveryModeTest.js`
     - [ ] liquidate(), with 110% < ICR < TCR, can claim collateral, re-open, be reedemed and claim again:
     - [ ] liquidate(), with 110% < ICR < TCR, can claim collateral, after another claim from a redemption:
     - [ ] batchLiquidateTroves(): skips liquidation of troves with ICR > TCR, regardless of Stability Pool size

**Comment by udosson** [comment]
merged in https://github.com/kumodao/kumo-protocol/pull/237
