### ISSUE TITLE
Change twitter link in front-end to the new one:  KUMO_dao -> kumo_earth

### ISSUE THREAD

**Issue by martinkrung** [kumodao/kumo-protocol#341]

**Comment by marceljay** [comment]
I just checked, this has been solved. 

Since we have 76 open Issues, it's important we keep this clean if we want to continue using it as our issue-tracking system. 

cc: @asimpk @arthurka-o @udosson

**Comment by marceljay** [comment]
I just checked, this has been solved. 

Since we have 76 open Issues, it's important we keep this clean if we want to continue using it as our issue-tracking system. 

cc: @asimpk @arthurka-o @udosson
