### ISSUE TITLE
Commitlint body length restrictions are too harsh

### ISSUE THREAD

**Issue by arthurka-o** [kumodao/kumo-protocol#384]
I imagined that a commit body should explain all nuances and details of the commit.
But right now the max length of the body is 100 symbols. And the max length of the line also 100 characters.
My biggest commit body is 374 chars. Maybe we should consider increasing limits?

The commit in the question: https://github.com/kumodao/kumo-protocol/pull/383/commits/c2efc4c01351e974e38c17c6b80e3cae4e2753f1

**Comment by marceljay** [comment]
I'm not sure what you mean here, the commit body is restricted in character length. 
Look at my commit here:
https://github.com/kumodao/kumo-protocol/commit/70cb4b061e303e1601c8b125f0dcb21805f374a9

The commit title though should be restrictred, but not sure `commitlint` does enforce this right now.

**Comment by arthurka-o** [comment]
Oh, I see. So we only restrict the line length, got it.
Probably was confused by an error message.
Thanks for the commit example 👍
