### ISSUE TITLE
Disabling SDK to get working build

### ISSUE THREAD

**Issue by arthurka-o** [kumodao/kumo-protocol#397]
Hi @marceljay 👋 
I have a question regarding SDK build and PR structure overall.
In my [PR](https://github.com/kumodao/kumo-protocol/pull/395), I made a few changes in smart contracts, and it broke SDK, tests, and docs.
I can skip tests and disable SDK and docs build, and fix them in the next PR. But I'm not sure that merging those changes in the `dev` is a good idea. If someone creates a new PR after my merge, they won't know if SDK was turned off. And they won't know if something was broken after their changes.
Is it okay to merge such changes? Is there a better way? I was thinking about a feature branch in the main repo.
I want to know your opinion.

cc: @asimpk @udosson

**Comment by marceljay** [comment]
Do you have a good understanding of what exactly broke the SDK test run?
Was it the outdated package? 
```
Browserslist: caniuse-lite is outdated. Please run:
```

**Comment by arthurka-o** [comment]
Yes. Run was broken because I turned off SDK build. And now front-end cannot build because cannot find some SDK files.
If I turn off the build of one of the packages, it can brake other. That's also why I don't want to merge those kind of changes into the `dev`.

**Comment by asimpk** [comment]
> Browserslist: caniuse-lite is outdated. Please run:

No, this package has no effect on the SDK build. As far I understand @arthurka-o saying that if he makes any changes in smart contracts, when He makes PR for those changes only SDK fails at GHA, (Why fail? Because SDK should be updated according to the changes in smart contracts where required). 
So the question is for making PR successful then it may become large or difficult to review.

**Comment by marceljay** [comment]
> Yes. Run was broken because I turned off SDK build. And now front-end cannot build because cannot find some SDK files. If I turn off the build of one of the packages, it can brake other. That's also why I don't want to merge those kind of changes into the `dev`.

I see, so in this case, i'm totally fine with opening the 2-3 PRs against a feature branch (e.g. `KIP-3-all` on which the SDK won't run.
