### ISSUE TITLE
Replace LUSD with KUSD in Front-end

### ISSUE THREAD

**Issue by udosson** [kumodao/kumo-protocol#53]
## Description
As a user of Kumo, I want to recognize the stablecoin `KUSD` in the front-end. I want to know what stablecoin I mint.

## Expected Outcome
- [x] Replace LUSD with KUSD on all front-end pages
- [x] Replace LUSD with KUSD in all hints

**Comment by wollooo** [comment]
done at [#66](https://github.com/kumodao/borrowprot/pull/66)
