### ISSUE TITLE
Replace LQYT with KUMO in Front-end

### ISSUE THREAD

**Issue by udosson** [kumodao/kumo-protocol#54]
## Description
As a user of Kumo, I want to recognize the `KUMO` token in the front-end. I want to know what governance token I can get, use, and hold.

## Expected Outcome
- [x] Replace `LQTY` with `KUMO` on all front-end pages
- [x] Replace `LQTY` with `KUMO` in all hints

**Comment by wollooo** [comment]
done at [#66](https://github.com/kumodao/borrowprot/pull/66)
