### ISSUE TITLE
Research UUPS Proxy Pattern

### ISSUE THREAD

**Issue by udosson** [kumodao/kumo-protocol#88]
## Description
As a smart contract developer, I want to gain a deep understanding of the upgradability of smart contracts.

## Expected Outcome
Proficient knowledge of the UUPS Proxy Pattern.
- [x] Read and understand the following resources: https://docs.openzeppelin.com/contracts/4.x/api/proxy, https://docs.openzeppelin.com/contracts/4.x/api/proxy, https://www.youtube.com/watch?v=kWUDTZhxKZI, https://www.youtube.com/watch?v=2T3vD5gFJAc, https://blog.openzeppelin.com/proxy-patterns/
- [ ] Followed the OpenZepplin UUPS Demo at https://forum.openzeppelin.com/t/uups-proxies-tutorial-solidity-javascript/7786
- [ ] Extend the demo with gnosis multi-sig wallet according to https://forum.openzeppelin.com/t/openzeppelin-upgrades-step-by-step-tutorial-for-hardhat/3580, https://forum.openzeppelin.com/t/tutorial-on-using-a-gnosis-safe-multisig-with-a-timelock-to-upgrade-contracts-and-use-functions-in-a-proxy-contract/7272
- [ ] Prepare 5 slides about the UUPS proxy patterns and showcase a demo of the UUPS proxy with gnosis safe

**Comment by udosson** [comment]
@wollooo could you add the steps that you think we should follow to make kumo upgradable?

**Comment by arthurka-o** [comment]
I think I've already got enough knowledge about UUPS pattern, so I'll close this
